# Module manifest for module 'image-builder-generator'
# Generated by: Javy de Koning
# Generated on: 1/3/20

@{
    # Script module or binary module file associated with this manifest.
    RootModule        = 'AWS.ImageBuilder.DocumentGenerator.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = 'cafa86d9-1e0c-47ec-bd10-c01360551b89'

    # Author of this module
    Author            = 'Javy de Koning'

    # Company or vendor of this module
    CompanyName       = 'Amazon Web Services'

    # Copyright statement for this module
    Copyright         = '(c) Amazon Web Services. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'EC2 Image Builder Component Document Generator. A PowerShell module to convert your Bash and PowerShell scripts into EC2 Image Builder Component Documents.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @('powershell-yaml')

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = 'New-ImageBuilderDocument', 'New-ImageBuilderPhase',
    'New-ImageBuilderS3Action', 'New-ImageBuilderRegistryAction', 'New-ImageBuilderStep'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = 'New-EC2IBDocument', 'IBDocument', 'IBD',
    'New-EC2IBPhase', 'IBPhase', 'IBP',
    'New-EC2IBS3Action', 'IBS3Action', 'IBS3A',
    'New-EC2IBRegAction', 'IBRegAction', 'IBRA',
    'New-EC2IBStep', 'IBStep', 'IBS'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('aws', 'ec2', 'image builder', 'ec2 image builder')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/awslabs/aws-image-builder-document-generator/master/LICENSE?token=ABB7XG3AFTZ4COQUMCCR5BC62TUGK'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/awslabs/aws-image-builder-document-generator'
        }
    }
}